### ISSUE TITLE
SwiphGiphyViewController only shows the search bar

### ISSUE THREAD

**Issue by Cortlandd** [52inc/SwiftyGiphy#9]
I read the code and saw the loadView() function which changes the navigation title, etc. But it seems that small part isn't being called. Also, the `controller.dismiss` function doesn't actually dismiss swiftgiphyviewcontroller.

```
class DetailViewController: UIViewController, UITextFieldDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate, SwiftyGiphyViewControllerDelegate  {
    
    func giphyControllerDidSelectGif(controller: SwiftyGiphyViewController, item: GiphyItem) {
        
        if let gifDownSized = item.downsizedImage {
            detailImageView.sd_setImage(with: gifDownSized.url)
        }
        
        // close gif selection controller via delegate. This doesn't work!
        controller.dismiss(animated: true)
    }
    
    func giphyControllerDidCancel(controller: SwiftyGiphyViewController) {
        print("hello")
    }
    
    var timerModel: TimerModel!
    
    // Bottom toolbar button on the detailviewcontroller page
    @IBAction func useGiphy(_ sender: UIBarButtonItem) {
        // Open the giphy search menu

        // A viewcontroller inside the storyboard with a segue from detailviewcontroller to a viewcontroller of type swiftygiphycontroller

        performSegue(withIdentifier: "gifSelectorSegue", sender: self)
    }
}
```

My DetailViewController does inherit UINavigationDelegate and SwiftyGiphyDelegate

<img width="318" alt="screen shot 2018-10-13 at 9 25 30 am" src="https://user-images.githubusercontent.com/6477843/46907134-b3841800-ced3-11e8-9561-d9f1264859a5.png">

**Comment by brendan09** [comment]
You need to present it inside a navigation controller. The navigation controller delegate on your detail view controller doesn’t matter. It must be presented in a navigation controller. You can’t segue directly to it unless it’s a “push” segue and your precious VC is already a child of a UINavigationController.

**Comment by brendan09** [comment]
I’ve said this 3-4 times already: None of these view controllers need to be a navigation controller. Please read what I’m writing carefully. 

You need to have SwiftyGiphy CONTAINED in a navigation controller, and then you present the navigation controller. Push works because your detail VC is currently contained in a navigation controller. When you modally present something, it’s a new context and you need to ensure that context has a navigation controller that SwiftyGiphy is in.

You also need to ensure you set SwiftyGiphy’s delegate property. Your detail view controller implementing the delegate is NOT enough.

The other project is doing these things, yours isn’t. 

Your setup should be: Segue (modally present) to a navigation controller that has a SwiftyGiphy view controller as it’s root view controller. Do not segue directly to SwiftyGiphy. Segue to a navigation controller that has SwiftyGiphy as it’s root view controller.

In your detail view controller you need to override prepareForSegue and determine if it’s rhe segue to the navigation controller containing SwiftyGiphy. If it is, assign your detail VC to SwiftyGiphy’s delegate property.

**Comment by Cortlandd** [comment]
As suggested, I've implemented a Navigation Controller with SwifyGiphyVC as the rootvc. Did some reading and that make sense now. 
```
    let del = SwiftyGiphyViewController()
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        switch segue.identifier {
        // ID of the modeally segue
        case "gifSelectorSegue"?:
            del.delegate = self
        default:
            preconditionFailure("Unexpected segue identifier.")
        }
    }
```

According to the code in the library itself. The line of code below is a global variable inside SwiftyGiphyViewController(). The above code checks for the relationship between detailvc and the nav controller but the delegate methods still aren't actually working. Which makes me believe I still haven't properly set detailvc as the delegate. But I'm confused why when in the above code I assign detaivc as the delegate
```public weak var delegate: SwiftyGiphyViewControllerDelegate?```

<img width="852" alt="screen shot 2018-10-13 at 1 39 47 pm" src="https://user-images.githubusercontent.com/6477843/46908820-213d3d80-ceee-11e8-9d14-c7bd8658ef1d.png">


Also, the Done button isn't working. I'm assuming a delegate thing. 
<img width="196" alt="screen shot 2018-10-13 at 1 45 01 pm" src="https://user-images.githubusercontent.com/6477843/46908828-3b771b80-ceee-11e8-91c1-f145c3751c14.png">

**Comment by brendan09** [comment]
In your prepare for segue method you’re creating a new SwiftyGiphy giphy VC and assigning yourself as it’s delegate. However, that instance of SwiftyGiphy isn’t the one the segue is using, so it ceases to exist as soon as the method exits.

The SwiftyGiphy instance the segue is using can be access via: “(segue.destination as? UINavigationController)?.viewControllers.first as? SwiftyGiphyViewController. 

That’ll be an optional, but that’s ok (you can unwrap it if you want). Assign your detail VC to that SwiftyGiphy view controller’s delegate.

**Comment by brendan09** [comment]
Awesome! Glad you got working.

**Comment by Cortlandd** [comment]
Question.

I'm at the point where I'm trying to cache the gif images in the detail view. With the approach I've implemented so far, regular still images works fine, but the gif images present an issue.

```
class ImageStore {
    
    let cache = NSCache<NSString, UIImage>()
    
    /*
     These three methods all take in a key of type String so that
     the code does not have to think about the underlying implementation of 
     NSCache. They can then cast each String
     to an NSString when passing it to the cache.
     */
    func setImage(_ image: UIImage, forKey key: String) {
        cache.setObject(image, forKey: key as NSString)
    }
    func image(forKey key: String) -> UIImage? {
        return cache.object(forKey: key as NSString)
    }
    func deleteImage(forKey key: String) {
        cache.removeObject(forKey: key as NSString)
    }

}
```
Caching a regular picked image:
```
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String: Any]) {
        
        // Get the picked image
        let image = info[UIImagePickerControllerOriginalImage] as! UIImage
        
        // Store the image in the ImageStore for the item's key
        imageStore.setImage(image, forKey: timerModel.imgKey)
        
        // Put the image to the screen in the detailImageView
        detailImageView.image = image
        
        // Take image picker off the screen you must call this dismiss method
        dismiss(animated: true, completion: nil)
}
```

Attempting to pass detailImageView.image as shown below presents an error as shown in the screenshow below.

```
func giphyControllerDidSelectGif(controller: SwiftyGiphyViewController, item: GiphyItem) {
        
        if let gifDownSized = item.downsizedImage {
            detailImageView.sd_setImage(with: gifDownSized.url)
            
            /* I NEED TO CACHE THIS GIF */
            
            // Store the image in the ImageStore for the item's key
            //imageStore.setImage(detailImageView.image, forKey: timerModel.imgKey)
        }
        
        print("TAPPED AN IMAGE")
        
        controller.dismiss(animated: true, completion: nil)
}
```
<img width="859" alt="screen shot 2018-10-14 at 10 31 35 am" src="https://user-images.githubusercontent.com/6477843/46918819-6e77e880-cf9c-11e8-9806-bf46c5ecc757.png">


Where exactly am I going wrong here? UIImage is passed in the cache variable passed in ImageStore and detailimageview.image is a ```uimage?```. Is there a more recommended approach or am I going about my initial implementation (learned from books I've been reading) all wrong considering my neds?

**Comment by brendan09** [comment]
The sd_setImage line tells it to start downloading the image and set it when done. This is an asynchronous process, so your main thread continues processing while that’s done in the background. As a result, your next line of code is hit before the image has finished downloading and is set. That means you’re trying to save nil, which your force unwrapped.

SDWebImage has a cache for images it downloads. Why are you implementing another cache rather than configuring the one already being used?

Since this isn’t SwiftyGipht  related, this is outside the scope of what I’ll be able to assist you with. I’d recommend looking to StackOverflow or reddit if you need help on async stuff or configuring SDWebImage.
